/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Bubla' at '14/12/16 16:33' with Gradle 3.2.1
 *
 * @author Bubla, @date 14/12/16 16:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
